### ISSUE TITLE
API key e-mail

### ISSUE THREAD

**Issue by gabrielfbueno** [yongghongg/stock-symbol#1]
I am not receiving my key in the email

**Comment by yongghongg** [comment]
Hi, Gabriel. I am sorry to hear that.
I will resend it to you (bielzeraaaw@gmail.com).

**Comment by gabrielfbueno** [comment]
> 

No problem, thank you.
Congratulations! your's API is very useful!

**Comment by sultanovazamat** [comment]
@yongghongg could you please check this email too (sae010@campus.mephi.ru), didn't receive an API key.
Thanks in advance!

UPD:

received an API key, thank you!

**Comment by yongghongg** [comment]
@sultanovazamat 
Thank you for signing up.
Sorry to hear that you didn’t receive the key.
Your email has been registered in the database and I have resent the key to you.
