### ISSUE TITLE
SXXP missing tickers

### ISSUE THREAD

**Issue by Biber76** [yongghongg/stock-symbol#2]
Hi there,

I downloaded the SXXP tickers. Should be almost 600 but only got:
['EDPR.LS', 'EDP.LS', 'JMT.LS', 'GALP.LS', 'MRL.LS'] with the following code
ss.get_symbol_list(index='SXXP', symbols_only=True)

Do I have to change anything or is it a bug?
Best regards,
Martin

**Comment by yongghongg** [comment]
@Biber76 
Hi there Martin.
It was a mistake from my side as I didn't realize there were multiple indexes with the name SXXP.
I have fixed it and now you should be able to get the full list of SXXP tickers in the database (551 tickers at the moment).

**Comment by Biber76** [comment]
Hi there,
Thank you for the fast solution. 
Please check your tickers. Some of the london exchange have two dots (for example BP..L) instead of one. That leads to the wrong companies or end in an error.
Thanks
Best regards,
Martin

**Comment by Biber76** [comment]
Hi there,
I just checked a few tickers. There are other tickers where the ending is probably wrong:
ELUX_A.ST, it should be ELUX-A.ST
Best regards,
Martin
